// <auto-generated />
using System;
using Euris.Aeroporti.ScaffoldExample.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Euris.Aeroporti.ScaffoldExample.Migrations
{
    [DbContext(typeof(AeroportiContext))]
    partial class AeroportiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Euris.Aeroporti.ScaffoldExample.Models.DB.Aeroporto", b =>
                {
                    b.Property<string>("Citta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NumPiste")
                        .HasColumnType("int");

                    b.HasKey("Citta")
                        .HasName("PK__Aeroport__878CD512E0D2AF38");

                    b.ToTable("Aeroporto", (string)null);
                });

            modelBuilder.Entity("Euris.Aeroporti.ScaffoldExample.Models.DB.Pilot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataDiNascita");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nome");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Cognome");

                    b.HasKey("Id")
                        .HasName("PK_PilotId");

                    b.ToTable("Piloti", (string)null);
                });

            modelBuilder.Entity("Euris.Aeroporti.ScaffoldExample.Models.DB.Plains", b =>
                {
                    b.Property<string>("PlainType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TipoAereo");

                    b.Property<int>("GoodsQuantity")
                        .HasColumnType("int")
                        .HasColumnName("QtaMerci");

                    b.Property<int>("PassengersNumber")
                        .HasColumnType("int")
                        .HasColumnName("NumPasseggeri");

                    b.HasKey("PlainType")
                        .HasName("PK__Aereo__7ADE5096CDA08E91");

                    b.ToTable("Aereo", (string)null);
                });

            modelBuilder.Entity("Euris.Aeroporti.ScaffoldExample.Models.DB.Volo", b =>
                {
                    b.Property<string>("IdVolo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CittaArr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CittaPart")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GiornoSett")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("OraArr")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("OraPart")
                        .HasColumnType("time");

                    b.Property<string>("TipoAereo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdVolo")
                        .HasName("PK__Volo__550D6D6DF0B59EAD");

                    b.HasIndex("CittaArr");

                    b.HasIndex("CittaPart");

                    b.HasIndex("TipoAereo");

                    b.ToTable("Volo", (string)null);
                });

            modelBuilder.Entity("PilotaVolo", b =>
                {
                    b.Property<string>("FlightsIdVolo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PilotsNavigationId")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("FlightsIdVolo", "PilotsNavigationId");

                    b.HasIndex("PilotsNavigationId");

                    b.ToTable("PilotaVolo", (string)null);
                });

            modelBuilder.Entity("Euris.Aeroporti.ScaffoldExample.Models.DB.Volo", b =>
                {
                    b.HasOne("Euris.Aeroporti.ScaffoldExample.Models.DB.Aeroporto", "CittaArrNavigation")
                        .WithMany("VoloCittaArrNavigations")
                        .HasForeignKey("CittaArr")
                        .IsRequired()
                        .HasConstraintName("FK__Volo__CittaArr__2E1BDC42");

                    b.HasOne("Euris.Aeroporti.ScaffoldExample.Models.DB.Aeroporto", "CittaPartNavigation")
                        .WithMany("VoloCittaPartNavigations")
                        .HasForeignKey("CittaPart")
                        .IsRequired()
                        .HasConstraintName("FK__Volo__CittaPart__2D27B809");

                    b.HasOne("Euris.Aeroporti.ScaffoldExample.Models.DB.Plains", "TipoPlainsNavigation")
                        .WithMany("Flights")
                        .HasForeignKey("TipoAereo")
                        .IsRequired()
                        .HasConstraintName("FK__Volo__TipoAereo__2F10007B");

                    b.Navigation("CittaArrNavigation");

                    b.Navigation("CittaPartNavigation");

                    b.Navigation("TipoPlainsNavigation");
                });

            modelBuilder.Entity("PilotaVolo", b =>
                {
                    b.HasOne("Euris.Aeroporti.ScaffoldExample.Models.DB.Volo", null)
                        .WithMany()
                        .HasForeignKey("FlightsIdVolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Euris.Aeroporti.ScaffoldExample.Models.DB.Pilot", null)
                        .WithMany()
                        .HasForeignKey("PilotsNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Euris.Aeroporti.ScaffoldExample.Models.DB.Aeroporto", b =>
                {
                    b.Navigation("VoloCittaArrNavigations");

                    b.Navigation("VoloCittaPartNavigations");
                });

            modelBuilder.Entity("Euris.Aeroporti.ScaffoldExample.Models.DB.Plains", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
