//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euris.AirportExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volo
    {
        public string IdVolo { get; set; }
        public string GiornoSett { get; set; }
        public string CittaPart { get; set; }
        public System.TimeSpan OraPart { get; set; }
        public string CittaArr { get; set; }
        public System.TimeSpan OraArr { get; set; }
        public string TipoAereo { get; set; }
    
        public virtual Aereo Aereo { get; set; }
        public virtual Aeroporto Aeroporto { get; set; }
        public virtual Aeroporto Aeroporto1 { get; set; }
    }
}
